INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Brasil');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Afeganistão');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Albânia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Argélia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Samoa Americana');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Andorra');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Angola');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Anguilla');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Antártida');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Antigua e Barbuda');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Argentina');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Armênia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Aruba');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Austrália');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Áustria');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Azerbaijão, Republica do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bahamas, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bahrein, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bangladesh');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Barbados');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Belarus, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bélgica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Belize');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Benin');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bermudas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Butão');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bolívia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bósnia-herzegovina (Republica da)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Botsuana');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bouvet, Ilha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Território Britânico do Oceano Indico');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Brunei');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bulgária, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Burkina Faso');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Burundi');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Camboja');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Camarões');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Canada');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Cabo Verde, Republica de');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Cayman, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Republica Centro-Africana');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Chade');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Chile');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'China, Republica Popular');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Christmas, Ilha (Navidad)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Cocos (Keeling); Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Colômbia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Comores, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Congo');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Congo, Republica Democrática do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Cook, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Costa Rica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Costa do Marfim');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Croácia (Republica da)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Cuba');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Chipre');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Tcheca, Republica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Dinamarca');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Djibuti');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Dominica, Ilha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Republica Dominicana');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Timor Leste');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Equador');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Egito');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'El Salvador');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guine-Equatorial');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Eritreia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Estônia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Etiópia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Falkland (Ilhas Malvinas)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Feroe, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Fiji');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Finlândia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Franca');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guiana francesa');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Polinésia Francesa');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Terras Austrais e Antárticas Francesas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Gabão');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Gambia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Georgia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Alemanha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Gana');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Gibraltar');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Grécia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Groenlândia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Granada');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guadalupe');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guam');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guatemala');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guine');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guine-Bissau');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guiana');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Haiti');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Ilha Heard e Ilhas McDonald');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Vaticano, Estado da Cidade do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Honduras');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Hong Kong');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Hungria, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Islândia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Índia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Indonésia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Ira, Republica Islâmica do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Iraque');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Irlanda');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Israel');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Itália');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Jamaica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Japão');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Jordânia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Cazaquistão, Republica do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Quênia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Kiribati');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Coreia, Republica Popular Democrática da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Coreia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Kuwait');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Quirguiz, Republica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Laos, Republica Popular Democrática do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Letônia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Líbano');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Lesoto');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Libéria');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Líbia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Liechtenstein');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Lituânia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Luxemburgo');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Macau');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Macedônia do Norte');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Madagascar');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Malavi');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Malásia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Maldivas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Mali');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Malta');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Marshall, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Martinica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Mauritânia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Mauricio');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Mayotte (Ilhas Francesas)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'México');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Micronesia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Moldávia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Mônaco');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Mongólia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Montserrat, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Marrocos');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Moçambique');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Mianmar (Birmânia)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Namíbia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Nauru');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Nepal');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Países Baixos (Holanda)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Nova Caledonia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Nova Zelândia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Nicarágua');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Níger');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Nigéria');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Niue, Ilha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Norfolk, Ilha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Marianas do Norte');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Noruega');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Oma');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Paquistão');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Palau');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Panamá');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Papua Nova Guine');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Paraguai');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Peru');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Filipinas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Pitcairn, Ilha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Polônia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Portugal');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Porto Rico');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Catar');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Reunião, Ilha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Romênia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Rússia, Federação da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Ruanda');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'São Cristovão e Neves, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Santa Lucia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'São Vicente e Granadinas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Samoa');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'San Marino');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'São Tome e Príncipe, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Arábia Saudita');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Senegal');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Seychelles');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Serra Leoa');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Cingapura');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Eslovaca, Republica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Eslovênia, Republica da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Salomão, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Somalia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'África do Sul');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Ilhas Geórgia do Sul e Sandwich do Sul');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Espanha');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Sri Lanka');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Santa Helena');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'São Pedro e Miquelon');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Sudão');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Suriname');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Svalbard e Jan Mayen');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Eswatini');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Suécia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Suíça');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Síria, Republica Árabe da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Formosa (Taiwan)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Tadjiquistao, Republica do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Tanzânia, Republica Unida da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Tailândia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Togo');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Toquelau, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Tonga');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Trinidad e Tobago');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Tunísia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Turquia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Turcomenistão, Republica do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Turcas e Caicos, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Tuvalu');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Uganda');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Ucrânia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Emirados Árabes Unidos');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Reino Unido');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Estados Unidos');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Ilhas Menores Distantes dos Estados Unidos');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Uruguai');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Uzbequistão, Republica do');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Vanuatu');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Venezuela');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Vietnã');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Virgens, Ilhas (Britânicas)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Virgens, Ilhas (E.U.A.)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Wallis e Futuna, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Saara Ocidental');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Iémen');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Iugoslávia, República Fed. da');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Zâmbia');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Zimbabue');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Guernsey, Ilha do Canal (Inclui Alderney e Sark)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Jersey, Ilha do Canal');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Man, Ilha de');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Montenegro');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Republika Srbija');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Sudao do Sul');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Zona do Canal do Panamá');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Palestina');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Aland, Ilhas');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Curaçao');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'São Martinho, Ilha de (Parte Holandesa)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Bonaire');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Antartica');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Ilha Herad e Ilhas Macdonald');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'São Bartolomeu');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'São Martinho, Ilha de (Parte Francesa)');
INSERT INTO paises (pai_id, pai_nome) VALUES (paises_seq.nextval, 'Terras Austrais e Antárcticas Francesas');